name: bus_track
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: '^2.31.0'
  cloud_firestore: '^4.17.3'
  email_validator: '^2.1.16'
  firebase_auth: '^4.19.5'



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/apple.png
    - assets/userimg.jpg

